name: Go Build and Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Debug - Show branch info
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
